{
  TString FileNameOut = "/data_CMS/cms/mperez/TauTrigger_data/2018CalibIsolation/turnOns_92X_v1_8_4_130518";
  FileNameOut += ".root";

  TString FileNameOut = "/data_CMS/cms/mperez/TauTrigger_data/2018CalibIsolation/turnOns_92X_v1_8_4_130518";
  FileNameOut += ".root";
  
  TString Threshold_NewLayer1_noIso = "38";
  TString Threshold_NewLayer1_Option1 = "23";
  TString Threshold_NewLayer1_Option2 = "30";
  TString Threshold_NewLayer1_Option3 = "31";
  TString Threshold_NewLayer1_Option4 = "32";
  TString Threshold_NewLayer1_Option5 = "34";
  TString Threshold_NewLayer1_Option6 = "36";
  TString Threshold_NewLayer1_Option7 = "36";
  TString Threshold_NewLayer1_Option8 = "28";
  TString Threshold_NewLayer1_Option9 = "37";
  TString Threshold_NewLayer1_Option10 = "37";
  TString Threshold_NewLayer1_Option11 = "37";
  TString Threshold_NewLayer1_Option12 = "38";
  TString Threshold_NewLayer1_Option13 = "38";
  TString Threshold_NewLayer1_Option14 = "38";
  TString Threshold_NewLayer1_Option15 = "34";
  TString Threshold_NewLayer1_Option16 = "38";
  TString Threshold_NewLayer1_Option17 = "38";
  TString Threshold_NewLayer1_Option18 = "38";
  TString Threshold_NewLayer1_Option19 = "38";
  TString Threshold_NewLayer1_Option20 = "38";
  TString Threshold_NewLayer1_Option21 = "35";
  TString Threshold_NewLayer1_Option22 = "30";
  TString Threshold_NewLayer1_noIso_old = "38";
  TString Threshold_NewLayer1_Option22_old = "30";

  //mode 
  /*TString Threshold_NewLayer1_noIso = "41";
  TString Threshold_NewLayer1_Option1 = "18";
  TString Threshold_NewLayer1_Option2 = "24";
  TString Threshold_NewLayer1_Option3 = "27";
  TString Threshold_NewLayer1_Option4 = "28";
  TString Threshold_NewLayer1_Option5 = "31";
  TString Threshold_NewLayer1_Option6 = "37";
  TString Threshold_NewLayer1_Option7 = "37";
  TString Threshold_NewLayer1_Option8 = "24";
  TString Threshold_NewLayer1_Option9 = "38";
  TString Threshold_NewLayer1_Option10 = "38";
  TString Threshold_NewLayer1_Option11 = "38";
  TString Threshold_NewLayer1_Option12 = "40";
  TString Threshold_NewLayer1_Option13 = "40";
  TString Threshold_NewLayer1_Option14 = "40";
  TString Threshold_NewLayer1_Option15 = "32";
  TString Threshold_NewLayer1_Option16 = "41";
  TString Threshold_NewLayer1_Option17 = "41";
  TString Threshold_NewLayer1_Option18 = "40";
  TString Threshold_NewLayer1_Option19 = "40";
  TString Threshold_NewLayer1_Option20 = "40";
  TString Threshold_NewLayer1_Option21 = "34";
  TString Threshold_NewLayer1_Option22 = "27";
  TString Threshold_NewLayer1_noIso_unpacked = "42";
  TString Threshold_NewLayer1_Iso_unpacked = "29";
*/
  TFile f_Stage2(FileNameOut.Data(),"READ");
  TGraphAsymmErrors* eff_Stage2_iso_noIso = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_noIso_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option1 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option1_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option2 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option2_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option3 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option3_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option4 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option4_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option5 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option5_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option6 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option6_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option7 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option7_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option8 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option8_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option9 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option9_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option10 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option10_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option11 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option11_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option12 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option12_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option13 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option13_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option14 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option14_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option15 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option15_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option16 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option16_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option17 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option17_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option18 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option18_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option19 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option19_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option20 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option20_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option21 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option21_by_pt");
  TGraphAsymmErrors* eff_Stage2_iso_Option22 = (TGraphAsymmErrors*)f_Stage2.Get("divide_pt_pass_Option22_by_pt");

  eff_Stage2_iso_noIso->SetLineWidth(2);
  eff_Stage2_iso_Option1->SetLineWidth(2);
  eff_Stage2_iso_Option2->SetLineWidth(2);
  eff_Stage2_iso_Option3->SetLineWidth(2);
  eff_Stage2_iso_Option4->SetLineWidth(2);
  eff_Stage2_iso_Option5->SetLineWidth(2);
  eff_Stage2_iso_Option6->SetLineWidth(2);
  eff_Stage2_iso_Option7->SetLineWidth(2);
  eff_Stage2_iso_Option8->SetLineWidth(2);
  eff_Stage2_iso_Option9->SetLineWidth(2);
  eff_Stage2_iso_Option10->SetLineWidth(2);
  eff_Stage2_iso_Option11->SetLineWidth(2);
  eff_Stage2_iso_Option12->SetLineWidth(2);
  eff_Stage2_iso_Option13->SetLineWidth(2);
  eff_Stage2_iso_Option14->SetLineWidth(2);
  eff_Stage2_iso_Option15->SetLineWidth(2);
  eff_Stage2_iso_Option16->SetLineWidth(2);
  eff_Stage2_iso_Option17->SetLineWidth(2);
  eff_Stage2_iso_Option18->SetLineWidth(2);
  eff_Stage2_iso_Option19->SetLineWidth(2);
  eff_Stage2_iso_Option20->SetLineWidth(2);
  eff_Stage2_iso_Option21->SetLineWidth(2);
  eff_Stage2_iso_Option22->SetLineWidth(2);

  eff_Stage2_iso_noIso->SetLineColor(kBlack);
  eff_Stage2_iso_Option1->SetLineColor(kMagenta);
  eff_Stage2_iso_Option2->SetLineColor(kBlue);
  eff_Stage2_iso_Option3->SetLineColor(kBlue);
  eff_Stage2_iso_Option4->SetLineColor(kCyan);
  eff_Stage2_iso_Option5->SetLineColor(kGreen);
  eff_Stage2_iso_Option6->SetLineColor(kOrange);
  eff_Stage2_iso_Option7->SetLineColor(kRed);
  eff_Stage2_iso_Option8->SetLineColor(kGreen);
  eff_Stage2_iso_Option9->SetLineColor(kCyan);
  eff_Stage2_iso_Option10->SetLineColor(kGreen);
  eff_Stage2_iso_Option11->SetLineColor(kOrange);
  eff_Stage2_iso_Option12->SetLineColor(kRed);
  eff_Stage2_iso_Option13->SetLineColor(kBlue+2);
  eff_Stage2_iso_Option14->SetLineColor(kBlue);
  eff_Stage2_iso_Option15->SetLineColor(kOrange);
  eff_Stage2_iso_Option16->SetLineColor(kMagenta+2);
  eff_Stage2_iso_Option17->SetLineColor(kOrange);
  eff_Stage2_iso_Option18->SetLineColor(kRed);
  eff_Stage2_iso_Option19->SetLineColor(kBlue+2);
  eff_Stage2_iso_Option20->SetLineColor(kBlue);
  eff_Stage2_iso_Option21->SetLineColor(kGreen);
  eff_Stage2_iso_Option22->SetLineColor(kRed);
 
  TMultiGraph *mgbest = new TMultiGraph();
  mgbest->Add(eff_Stage2_iso_noIso,"l");
 // mgbest->Add(eff_Stage2_iso_Option1,"l");
  //mgbest->Add(eff_Stage2_iso_Option2,"l");
 // mgbest->Add(eff_Stage2_iso_Option8,"l");
 // mgbest->Add(eff_Stage2_iso_Option15,"l");
  mgbest->Add(eff_Stage2_iso_Option22,"l");
 
  TCanvas cbest("turnOns_newbest","turnOns_newbest",800,800);
  cbest.SetGrid();
  mgbest->Draw("same");
  mgbest->GetXaxis()->SetLabelSize(0.025);
  mgbest->GetYaxis()->SetLabelSize(0.025);
  mgbest->GetXaxis()->SetTitle("p_{T}^{offl} [GeV]");
  mgbest->GetXaxis()->SetTitleOffset(1.1);
  mgbest->GetXaxis()->SetRangeUser(18.,100.);
  mgbest->GetYaxis()->SetTitleOffset(1.4);
  mgbest->GetYaxis()->SetTitle("Single-#tau efficiency");
  mgbest->SetTitle("");

  TPaveText* texl = new TPaveText(0.2,0.86,0.93,0.98,"NDC");
  texl->AddText("CMS Internal, #sqrt{s}=13 TeV, MC VBF H #rightarrow #tau#tau (PU 28-62)");
  texl->SetTextSize(0.03);
  texl->SetFillStyle(0);
  texl->SetBorderSize(0);
  texl->Draw("same");

  TLegend* legbest = new TLegend(0.5,0.25,0.90,0.35);
  legbest->SetBorderSize(0);
  //legbest->SetHeader("caloStage2Params_2017_v1_10_mean_inconsistent");
  legbest->SetTextSize(0.023);
  legbest->AddEntry(eff_Stage2_iso_noIso ,"no-iso (E_{T}^{L1}#geq "+Threshold_NewLayer1_noIso +" GeV)","L");
//  legbest->AddEntry(eff_Stage2_iso_Option1,"iso Option 1 (E_{T}^{L1}#geq "+Threshold_NewLayer1_Option1+" GeV)","L");
  //legbest->AddEntry(eff_Stage2_iso_Option2,"#bf{2017 iso (E_{T}^{L1}#geq "+Threshold_NewLayer1_Option2+" GeV) - Option 2}","L");
 // legbest->AddEntry(eff_Stage2_iso_Option8,"iso Option 8 (E_{T}^{L1}#geq "+Threshold_NewLayer1_Option8+" GeV)","L");
 // legbest->AddEntry(eff_Stage2_iso_Option15,"iso Option 15 (E_{T}^{L1}#geq "+Threshold_NewLayer1_Option15+" GeV)","L");
  legbest->AddEntry(eff_Stage2_iso_Option22,"iso Option 22 (E_{T}^{L1}#geq "+Threshold_NewLayer1_Option22+" GeV)","L");
  legbest->Draw("same");

  texl->Draw("same");
 
  TString PlotNamesOutbest = "/data_CMS/cms/mperez/TauTrigger_data/2018CalibIsolation/TurnOns_92X_v1_8_4_130518_Opt22";
  TString PlotNamesOutPdfbest = PlotNamesOutbest;
  PlotNamesOutPdfbest += ".pdf";
  TString PlotNamesOutRootbest = PlotNamesOutbest;
  PlotNamesOutRootbest += ".root";
  cbest.SaveAs(PlotNamesOutPdfbest.Data());
  cbest.SaveAs(PlotNamesOutRootbest.Data());

}
